CC = gcc
LD = gcc
CFLAGS = -Wall
MOREFLAGS = -O2 -m486 -s
#MOREFLAGS = -g
LIBRARY =
PROGNAME = gbahdr.exe

OBJS = obj/main.o

default: $(OBJS)
	$(LD) $(CFLAGS) $(MOREFLAGS) -o $(PROGNAME) $(OBJS) $(LIBRARY)

$(OBJS): obj/%.o: src/%.c
	$(CC) $(CFLAGS) $(MOREFLAGS) -o $@ -c $<

main.o:    main.c     global.h main.h   functs.h

clean:
	rm -f obj/*.o $(PROGNAME)
