document.write('<a href="sonsiteawards.html"><SPAN TITLE="Annual Awards Ceremony - the Biggest Sonic event EVER!" litUp1><b>Sonic Site A');
document.write('wards</span></b></a><br><a href="monthaward.html"><b><SPAN TITLE="Unlike the biggie (Sonic Site Awards), a monthly c');
document.write('elebration where you can win an award for your site, and see the Sonic Stadium\'s awards!" litUp1>Site Monthly Awards</sp');
document.write('an></b></a><br><a href="10thanniv.html"><b><SPAN TITLE="Take a trip back in time and go thorugh Sonic\'s history, Seg');
document.write('a\'s history, rivals to Sega and Sonic and what the future hold for the blue spiny one." litUp1>10th Anniversary Page</sp');
document.write('an></b></a><br><!! -- News -- !!><a href="https://web.archive.org/20020118000000/http://tssz.emulationzone.org/news.htm" target=_blank><b><SPAN TIT');
document.write('LE="Sonic News as it Happens!" litUp1>Sonic News - Via TSSZ</span></b></a><br><!! -- Games -- !!><a href="games.');
document.write('html"><b><SPAN TITLE="The original Back Catalogue, pages upon pages of dedicated, uncompromised Sonic game info. Often c');
document.write('opied but never beaten on quality!" litUp1>Sonic Game Info List</b></span></a><br><a href="sonadv2intro.html"><b><SPAN');
document.write(' TITLE="See the biggest Sonic game to date!" litUp1>Sonic Adventure 2 - DC</span></b></a><br><a href="sonadvanceintro.');
document.write('html"><b><SPAN TITLE="Find out how the GBA debut Sonic game is getting on!" litUp1>Sonic Advance - GBA</span></b></a><br');
document.write('><a href="sonadv2bintro.html"><b><SPAN TITLE="The GameCube rendition of SA2 - unmissable!" litUp1>SA2 Battle - GC</spa');
document.write('n></b></a><br><a href="oddgames.html"><b><SPAN TITLE="Find out about all the games that were never released, hacks, ca');
document.write('nned games, betas, you name it..." litUp1>Secret Game Info</span></b></a><br><a href="sononline.html"><b><SPAN TITLE="');
document.write('Play Sonic games online, obviously ^_^. *Needs Flash to run*" litUp1>Online Sonic Games</span></b></a><br><a href="cha');
document.write('omain.html"><b><SPAN TITLE="You all know them - those cute things you breed in SA and SA2. Find out all the tactics here');
document.write('." litUp1>Chao Information</span></b></a><br><!! -- Sonic merchandise -- !!><a href="sonteamain.html"><b><SPAN T');
document.write('ITLE="Info on the biggest development company ever, and the games other than Sonic that has been created." litUp1>Sonic ');
document.write('Team Section</span></b></a><br><a href="merchandise.html"><b><SPAN TITLE="Sonic has become every single item known t');
document.write('o man! Find out the merchandise info on Sonic inside..." litUp1>Merchandise</span></b></a><br><a href="shop.html"><b');
document.write('><SPAN TITLE="Dread has brought his trusty Sonic shop back, full of Sonic merchandise and other items to buy" litUp1>Onl');
document.write('ine Sonic Shop</span></b></a><br><a href="cartoonsmain.html"><b><SPAN TITLE="Get the lowdown on cartoons such as AoS');
document.write('tH, SatAM, and Underground, and more." litUp1>Sonic Cartoon Info</span></b></a><br><a href="comicsmain.html"><b><SPA');
document.write('N TITLE="Helped Sonic\'s success, here\'s the section for Sonic comics such as STC and Archie." litUp1>Sonic The Comics</s');
document.write('pan></b></a><br><!! -- D/ls -- !!><a href="download.html"><b><SPAN TITLE="Wallpapers, Winamp Skins, Fonts, movie');
document.write('s and much more!" litUp1>Downloads</span></b></a><br><!! -- Sonic Fan Club -- !!><a href="sonfan.html"><b><SPAN ');
document.write('TITLE="This is the massive section dedicated to all Fan created things of Sonic. Fan Art, Fan Fics, Fan Games, hoaxes...');
document.write(' Feel free to submit your own Fan stuff here!" litUp1>SFC - Fan Section</span></b></a><br><a href="booksmain.html"><');
document.write('b><SPAN TITLE="The heads up on Sonic literature, including Game Books, Annuals and story books." litUp1>Sonic Stories/Bo');
document.write('oks</span></b></a><br><!! -- Cheats -- !!><a href="cheat.html"><b><SPAN TITLE="Wanna cheat? Of course you do - h');
document.write('ere\'s the greatest tips section around! Full of regular cheats, codes and hints!" litUp1>Sonic Game Cheats</span></b></a');
document.write('><br><a href="walkthroughs.html"><b><SPAN TITLE="Complete walkthrough guides to Sonic games, or submit your own." litU');
document.write('p1>Sonic Walkthroughs</span></b></a><br><a href="https://web.archive.org/20020118000000/http://sa2guide.topcities.com/sa2guide.html"><b><SPAN TITLE="The DEFI');
document.write('NITIVE guide to SA2 you\'ll ever need" litUp1>Ultimate SA2 Guide</span></b></a><br><!! -- Music -- !!><a href="mu');
document.write('sic.html"><b><SPAN TITLE="Hear mp3s, midis, RealAudio, and read lyrics! Definitive Music section!" litUp1>Sonic Music Zo');
document.write('ne</span></b></a><br><a href="dictionary.html"><b><SPAN TITLE="Massive dictionary of Sonic terms, Sonic worlds, and ');
document.write('profiles on all of the Sonic characters. Winner!" litUp1>Sonic Encyclopaedia</span></b></a><br><!! -- Artwork -- !!>');
document.write('<a href="official.html"><b><SPAN TITLE="Everything from Box Art to Screenshots, Sprites to Album covers and Official');
document.write(' Sonic Team Art can be found in here!" litUp1>Sonic Artwork Archive</span></b></a><br><a href="addacaption.html"><b>');
document.write('<SPAN TITLE="Humourous Sonic screenshots - all you have to do is add your own caption. Funny stuff." litUp1>Add a captio');
document.write('n</span></b></a><br><a href="interviews.html"><b><SPAN TITLE="Dread catches up with the best in the Sonic community,');
document.write(' plus other interviews." litUp1>Sonic Interviews</span></b></a><br><!! -- Fun Stuff -- !!><a href="sonuniverse.h');
document.write('tml"><b><SPAN TITLE="Find where all the towns and cities such as Robotropolis and Green Hill Zone are in this handy Soni');
document.write('c Universe map!" litUp1>Sonic World Locations</span></b></a><br><a href="petitions.html"><b><SPAN TITLE="This is the p');
document.write('lace to hear about Sonic online petitions that are going on." litUp1>Sonic Petitions Page</span></b></a><br><a href="l');
document.write('eague.html"><b><SPAN TITLE="Think you\'re the best Sonic gamesplayer? We have the whole world telling you otherwise! Prov');
document.write('e your worth here!" litUp1>Sonic Game Challenges</span></b></a><br><a href="askdread.html"><b><SPAN TITLE="Have a Soni');
document.write('c question, or even a site question? Dr. Dre(ad) will get you diagnosed immediately." litUp1>Ask Dr. Dre(ad)</span></b><');
document.write('/a><br><a href="https://web.archive.org/20020118000000/http://sonicfanatic.zzn.com" target=_blank><b><SPAN TITLE="Grab your exclusive FREE Sonicfanatic.zzn.c');
document.write('om email address!" litUp1>Free e-mail!</span></b></a><br><!! -- Links -- !!><a href="linksmain.html"><b><SPAN TI');
document.write('TLE="Want to see other Sonic sites? What if you want to submit a site to the Stadium? Not a problem!" litUp1>Sonic Links');
document.write(' Archive</span></b></a><br><!! -- Misc -- !!><a href="messageboard.html"><b><SPAN TITLE="Great place to chat to ');
document.write('others - includes Sega Sonic related and Fan submission forums, you can even help in creating Fan Fics online!" litUp1>M');
document.write('essage Board Forums</span></b></a><br><a href="sitemap.html"><b><SPAN TITLE="Getting stuck with the new Sonic Stad');
document.write('ium layout? Have no fear - this page will be able to help!" litUp1>Site Map</span></b></a><br><a href="sitehistory.htm');
document.write('l"><b><SPAN TITLE="Learn all about this site\'s history, you\'ll be surprised!" litUp1>Site History</span></b></a><br><a');
document.write(' href="updates.html"><b><SPAN TITLE="A collection of past Updates in this site, so you can check what you\'ve missed." li');
document.write('tUp1>Past Updates</span></b></a><br><a href="pastlayouts.html"><b><SPAN TITLE="Take a peekster at all the past layouts');
document.write(' that have been used for the Stadium, but gotten rid of later." litUp1>Old Site Layouts</span></b></a><br><hr width=');
document.write('100%><b><font size=3 color=red>Other Stuff...</font></b><br><font size=2><a href="https://web.archive.org/20020118000000/http://listen.to/segasonic" target');
document.write('=_blank><b><SPAN TITLE="Listen to the BEST Radio Station online!" litUp1>Sega Sonic Radio</SPAN></b></a><br><a');
document.write(' href="chat.html" target=_blank><b><SPAN TITLE="Chat to people instantaneously!" litUp1>AIM Chat Room</span></b></a><br>');
document.write('<a href="https://web.archive.org/20020118000000/http://htmlgear.lycos.com/guest/control.guest?u=dreadknux&i=1&a=sign" target=_blank><b><SPAN TITLE="Prove you');
document.write(' were here!" litUp1>Sign Guestbook</span></b></a><br><a href="https://web.archive.org/20020118000000/http://htmlgear.lycos.com/guest/control.guest?u=dreadknu');
document.write('x&i=1&a=view" target=_blank><b><SPAN TITLE="See the others that signed!" litUp1>View Guestbook</span></b></a><br><a ');
document.write('href="uniform.html"><b><SPAN TITLE="How to Contact Dread!" litUp1>Contact Information</span></b></a><p><P ALIGN=');
document.write('CENTER><div align=center><font size=1 color=#00B700><b>Please vote for my site!!</font><br><A HREF="https://web.archive.org/20020118000000/http://www.top');
document.write('sitelists.com/topsites.cgi?ID=227&user=sth&area=games" target=_blank><IMG SRC="https://web.archive.org/20020118000000/http://www.teamartail.com/link/top50.gif"');
document.write(' border=0></A><br><!-- BEGIN Sonic Top 50 CODE --><a href="https://web.archive.org/20020118000000/http://www.ultimatetopsites.com/bin/topsite.cgi?sonic&c');
document.write('at=general&ID=43" target=_blank><img src="https://web.archive.org/20020118000000/http://www.ultimatetopsites.com/bin/votepicture.cgi?sonic&cat=general&ID=43"');
document.write(' border=0></a><!-- END Sonic Top 50 CODE -->');